### ISSUE TITLE
AzureML Studio Dataset as source

### ISSUE THREAD

**Issue by CarlosAbramo** [Azure/Azure-TDSP-Utilities#10]
Hi,

In this current release only flat files and SQL Server query result sets can be used as source for IDEAR. Is there any plan to allow IDEAR to connect to a transient data set (after initial cleansing and transforming) in AML Studio ?

Best regards,

Carlos Abramo

**Comment by hangzh-msft** [comment]
Hi, Carlos,

Good point. We will add this request to our backlog and prioritize it in our future work. 

Currently, you can use the [AzureML R library](ftp://cran.r-project.org/pub/R/web/packages/AzureML/AzureML.pdf) to download the dataset from AML workspace to your local machine, and start using IDEAR to visualize and explore the data. 

Thanks,

Hang
