### ISSUE TITLE
reuse existing environment?  scalability plans?

### ISSUE THREAD

**Issue by robmccan** [Azure/Azure-TDSP-Utilities#11]
Hi,

IDEAR seems like a very cool tool...thanks for sharing.  A couple questions...

I already have a couple versions of R installed on my machine (MS R Server, In-SQL & Stand-Alone), as well as R Tools for VS.  Is it possible to use your IDEAR tool within that environment, or am I going to have to install yet more?

Also, do you have plans to make the IDEAR tool not limited by in-memory data frames?  I've been computing with RevoScaleR just for this purpose, and it would be great to not have to backtrack.  For some things sampling will work (e.g., first-order stats), but for others sampling is undesirable (e.g., outliers).

Thanks.

-Rob

**Comment by xibingaomsft** [comment]
Hi Rob,
Thanks for your feedbacks. 
1. IDEAR can work with RTVS. We will release a new documentation on how IDEAR works in RTVS in the near future. 
2. We are currently conducting thorough testing of IDEAR in different R environments.
3. Extending IDEAR to RevoScaleR is in the roadmap. Implementation may depend on user requests and other priorities.
Stay tuned!
