### ISSUE TITLE
IDEAR's Server param

### ISSUE THREAD

**Issue by robmccan** [Azure/Azure-TDSP-Utilities#12]
Sorry if this is a silly issue...  I'm trying to apply IDEAR on some data I have in a local SQL Server 2016 instance (everything is running on the same box, an Azure VM).  I followed your directions for creating a .yaml but I must be messing up on the Server parameter.  When I run IDEAR and select the .yaml, IDEAR keeps returning "Error: first argument is not an open RODBC channel".

So, what exactly should my argument be for the default SQL Server on the local box?  My various attempts at using localhost didn't work.

I can query the DB just fine from SSMS, so the DB is alive and functional.  I can also run IDEAR on your example datasets (para-adult.yaml and para-bike-rental.yaml), so the R/IDEAR side is also functional.

Any help would be appreciated, thanks.

**Comment by xibingaomsft** [comment]
Rob, have you followed the parameter settings specified at
https://github.com/Azure/Azure-TDSP-Utilities/blob/master/DataScienceUtilities/DataReport-Utils/team-data-science-process-idear-instructions.md ?
The second table from the doc above has the required params for SQL Server/DW data source.

**Comment by gopitk** [comment]
Rob, Is this still an issue? Usually the problem you may be trying to connect over TCP in RODBC and TCP protocol is disabled on SQL Server (by default). SSMS can use TCP or named pipes. To confirm this you can go to the SQL 2016 configuration utility and check the protocols enabled.

**Comment by hangzh-msft** [comment]
Closed this issue since the customer did not respond. Will reopen as needed.
