### ISSUE TITLE
An Error message when running the script Run-IDEAR.R .

### ISSUE THREAD

**Issue by BertJhuang** [Azure/Azure-TDSP-Utilities#15]
My environment:
1. R V3.3.1
2. RStudio V1.0.136

To start IDEAR,
I run the script "Run-IDEAR.R" in RStudio,but there is an error message on the shinny browser
"Error: missing value where TRUR/FALSE needed"

Any help would be appreciated, thanks.

**Comment by xibingaomsft** [comment]
Can you please provide the session info and the complete error message from RStudio console?

**Comment by BertJhuang** [comment]
> installed_packages <- rownames(installed.packages())
> if (!"rmarkdown" %in% installed_packages){
+   install.packages("rmarkdown")
+ }
> if (!"shiny" %in% installed_packages){
+   install.packages("shiny")
+ }
> 
> library(rmarkdown)
> script.dir <- dirname(sys.frame(1)$ofile)
**Error in sys.frame(1) : not that many frames on the stack**
> setwd(script.dir)
**Error in setwd(script.dir) : object 'script.dir' not found**
> rmdfile = "IDEAR.rmd"
> rmarkdown::run(rmdfile)
**Error in yaml::yaml.load(string, ...) : 
  Scanner error: while scanning a simple key at line 3, column 1could not find expected ':' at line 4, column 1**

**Comment by xibingaomsft** [comment]
1.  For error:  "Error in sys.frame(1) : not that many frames on the stack", you may have tried to execute code in Run-IDEAR.R line by line. This issue should be resolved if you source Run-IDEAR.r by clicking 'Source' in RStudio.
2. For error, "Error in yaml::yaml.load(string, ...) ", it shows that your yaml file may have some formatting issues. You can find an example yaml [here](https://github.com/Azure/Azure-TDSP-Utilities/blob/master/DataScienceUtilities/DataReport-Utils/para-adult.yaml)
