### ISSUE TITLE
BinaryClassification_UCI_Income.yaml incorrectly ordered.

### ISSUE THREAD

**Issue by amwahl** [Azure/Azure-TDSP-Utilities#16]
The example BinaryModelSelection.rmd file is throwing an error when executing on the BinaryClassification_UCI_Income.yaml.  The issue occurs because the parameter grid for runXgBoost is created with switched values of xgBoostsubsample and min_child_weight.  The indexing should be switched  to match the order of those parameters in the yaml (or the order of the parameters in the yaml should be switched).

**Comment by Pelonza** [comment]
Confirmed... I ran into this too when trying to use the UCI yaml file as a template.

**Comment by deguhath** [comment]
Thanks for reporting this issue. What package version are you using for xgboost?

**Comment by Pelonza** [comment]
This error has nothing to do with the xgboost package. It has to do with the ordering you read in the parameters for the xgboost from the yaml file.

You just have them indexed differently than the actual ordering in the yaml file.

**Comment by deguhath** [comment]
Noted and fixed the issue in yaml file. Thanks for pointing it out.

**Comment by Pelonza** [comment]
Note, even with that fixed, I was having issues getting the AMR to run to
completion on the UCI data... I don't know about the original user.

Specifically, when I run even the UCI yaml, I'm now getting that the data
has a new factor.

Again, I think this could be fixed easily, but you'll need to either
refactor your country data in the file...or delete data....



To schedule a meeting or appointment try:
https://karlrbschmitt.youcanbook.me/

Dr. Karl Schmitt
Assistant Professor
Department of Mathematics and Statistics
Department of Computing and Information Sciences
Director of Data Science Program
Director of Analytics and Modeling Graduate Program
Valparaiso University, Indiana

**Comment by Pelonza** [comment]
I actually had a lot of problems with using your "turn into factor" columns
setup.

R doesn't seem to like to turn array-indexed variables into factors, it
prefers extracting them as attributes of a data.frame that is:

trainDF['column']<-as.factor(trainDF['column'] )   : Generates listing error
trainDF$column<-as.factor(trainDF$column)      : Does not generate an error

Fixing these lines in your markdown file might fix the Honduras problem
also....

To schedule a meeting or appointment try:
https://karlrbschmitt.youcanbook.me/

Dr. Karl Schmitt
Assistant Professor
Department of Mathematics and Statistics
Department of Computing and Information Sciences
Director of Data Science Program
Director of Analytics and Modeling Graduate Program
Valparaiso University, Indiana

**Comment by deguhath** [comment]
If you want to submit a pull request with your code fixes, please do so. We can test and merge. Thanks.

**Comment by deguhath** [comment]
I have commented in the BinaryModelSelection.rmd markdown file for the users to try this convention - trainDF$column, if existing code breaks in their R version. Thanks for raising and explaining this issue.
