### ISSUE TITLE
[IDEAR] "subscript out of bounds" error

### ISSUE THREAD

**Issue by lucazav** [Azure/Azure-TDSP-Utilities#17]
Hi all,

I tried to load the data I get in this page:

[http://lib.stat.cmu.edu/datasets/irish.ed](http://lib.stat.cmu.edu/datasets/irish.ed)

Here is the csv file I'm using.
[irish_educational_transitions_data.zip](https://github.com/Azure/Azure-TDSP-Utilities/files/814097/irish_educational_transitions_data.zip)

The yaml file I'm using is this one:

```
DataFilePath:
    'Z:/<my_path>/irish_educational_transitions_data.csv'
HasHeader:
    Yes
Separator:
    ','
CategoricalColumns:
    - sex
    - educational_level
    - leaving_certificate
    - type_school
NumericalColumns:
    - dvrt
    - father_occupation_score
Target:
    leaving_certificate
RLogFilePath:
    irish_educational_transitions_data.log.r
```

I'm getting this error:

> Quitting from lines 1130-1251 (IDEAR.rmd) 
> 
> Warning: Error in [: subscript out of bounds
> Stack trace (innermost first):
>     118: eval [<text>#28]
>     117: eval
>     116: withVisible
>     115: withCallingHandlers
>     114: handle
>     113: timing_fn
>     112: evaluate_call
>     111: evaluate::evaluate
>     110: in_dir
>     109: block_exec
>     108: call_block
>     107: process_group.block
>     106: process_group
>     105: withCallingHandlers
>     104: process_file
>     103: knitr::knit
>     102: <Anonymous>
>     101: do.call
>     100: contextFunc
>      99: .getReactiveEnvironment()$runWith
>      98: shiny::maskReactiveContext
>      97: <reactive>
>      86: doc
>      85: shiny::renderUI
>      84: func
>      83: origRenderFunc
>      82: output$__reactivedoc__
>       7: <Anonymous>
>       6: do.call
>       5: rmarkdown::run
>       4: eval [Z:/SolidQ/Tools/Azure-TDSP-Utilities-master/DataScienceUtilities/DataReport-Utils/Run-IDEAR.R#13]
>       3: eval
>       2: withVisible
>       1: source

What's happened?

Thank you.

**Comment by xibingaomsft** [comment]
Hi lucazav, thanks for reporting this issue. It was due to a "index of out bounds error" in the PCA section, and now it is fixed. Please try again and let us know if you have further questions.

**Comment by lucazav** [comment]
Thank you!

**Comment by hangzh-msft** [comment]
Closed since issue has been fixed.
