### ISSUE TITLE
RUN- IDEAR.R Warning: Error in if: argument is of length zero

### ISSUE THREAD

**Issue by thomasbanyan** [Azure/Azure-TDSP-Utilities#23]
Im getting the flowing error, below the erro is my yaml file

label: unnamed-chunk-18 (with options) 
List of 3
 $ echo   : logi FALSE
 $ message: logi FALSE
 $ warning: logi FALSE

Quitting from lines 1391-1535 (IDEAR.rmd) 

Warning: Error in if: argument is of length zero

YAML
DataFilePath:
   ptpprogramdata.csv
HasHeader:
    Yes
Separator:
    ','
CategoricalColumns:
    - ProgramName
    - TeamName
    - TypeType
    - LOC
    - LOCDesc
    - ReferralSourceType
    - TargetedReferral
    - DischargeReason
    - discharge_revocation
    - DeathInOurCare
    - LifeExpectancy
    - FinancialClass
    - ProgramStatus
NumericalColumns:
    - LOS
    - STC
ColumnsToExclude:
    - pt_program_id
    - client_id
RLogFilePath:
    ptprogram2.log.r

**Comment by xibingaomsft** [comment]
Can you share your data as well? Alternatively, you can follow the step in the debugging guide to see what's wrong [https://github.com/Azure/Azure-TDSP-Utilities/wiki/Debugging-Guide-for-IDEAR-(R-Version)](https://github.com/Azure/Azure-TDSP-Utilities/wiki/Debugging-Guide-for-IDEAR-(R-Version))

**Comment by mustafakasap** [comment]
Can you check if there is a "Target" field in your YAML file?
