### ISSUE TITLE
Data Exploration without Target key in YAML file

### ISSUE THREAD

**Issue by mustafakasap** [Azure/Azure-TDSP-Utilities#24]
If you don't have Target field in your YAML file,

following line 1392 in IDEAR.rmd file fails as there is neither FALSE no TRUE in the if clause:

if(((config$Target %in% config$CategoricalColumns) & length(config$CategoricalColumns) > 1) | (!(config$Target %in% config$CategoricalColumns) & length(config$CategoricalColumns)>=1))

**Comment by hangzh-msft** [comment]
Thanks for reporting this. This bug has been fixed. Please git pull and retry it. 

Close now.
