### ISSUE TITLE
Enhancement: Separate Plotting

### ISSUE THREAD

**Issue by Pelonza** [Azure/Azure-TDSP-Utilities#27]
We run into an issue recently where we wanted to increase the font size on some of the plots, specifically the pie plots.

I am not sure I see the extra value in nesting and hiding the combined plot call. I would suggest just pulling the plot calls directly into the notebook. this would more easily facilitate a user pulling the notebook code chunk out and reproducing/modifying the plot. 

Another thing to consider would be a move to bokeh for the visualizations to allow more interaction and adjustment of the plots before exporting them.

**Comment by xibingaomsft** [comment]
Thanks for the suggestions. We will put those in our backlogs and also feel free to send pull request with your features and bug fixes.
