### ISSUE TITLE
Generate Report Error - Quitting from lines 10-100 (adult.log.spin.Rmd) 

### ISSUE THREAD

**Issue by ZellW** [Azure/Azure-TDSP-Utilities#30]
Hi Team!

While generating the Final Report, the following occurs.  Has anyone else experienced this and found a fix?

* installing *source* package 'knitr' ...
** package 'knitr' successfully unpacked and MD5 sums checked
** R
** demo
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (knitr)
Quitting from lines 10-100 (adult.log.spin.Rmd) 

Warning: Error in file: cannot open the connection
Stack trace (innermost first):
    94: file
    93: read.table
    92: read.csv
    91: eval [<text>#31]
    90: eval
    89: withVisible
    88: withCallingHandlers
    87: handle
    86: timing_fn
    85: evaluate_call
    84: evaluate
    83: in_dir
    82: block_exec
    81: call_block
    80: process_group.block
    79: process_group
    78: withCallingHandlers
    77: process_file
    76: knitr::knit
    75: rmarkdown::render
    74: eval [<text>#17]
    73: eval
    72: withProgress
    71: observeEventHandler [<text>#16]
     7: <Anonymous>
     6: do.call
     5: rmarkdown::run
     4: eval [~/GitHub/MS_TDSP/IDEAR/Run-IDEAR.R#13]
     3: eval
     2: withVisible
     1: source

**Comment by xibingaomsft** [comment]
It seems like the data file path in yaml file is not specified correctly.
