### ISSUE TITLE
Error: object 'cat_columns' not found

### ISSUE THREAD

**Issue by lucazav** [Azure/Azure-TDSP-Utilities#31]
Hi all,

I'm using the 0.12 version. I'm importing the csv file through the yaml file you can find as attachment.
I'm getting the "Error: object 'cat_columns' not found".

Is there something wrong in the yaml file?

Thank you.
[Price Elasticity.zip](https://github.com/Azure/Azure-TDSP-Utilities/files/1285234/Price.Elasticity.zip)

**Comment by lucazav** [comment]
The file works well with the version 0.11.
Thanks.

**Comment by xibingaomsft** [comment]
Thanks for the reporting. I can run latest version of IDEAR with your dataset without problem.

**Comment by lucazav** [comment]
Thank you, I’ll try it ASAP.

--
Luca Zavarella │ Business Intelligence & Advanced Analytics Technical Director | Data Science MPP |   SolidQ<http://www.solidq.com/> │ +39 02.86337532 phone | +39 366.9215162 mobile | +39 02.87085210 fax
