### ISSUE TITLE
IDEAR Updates?

### ISSUE THREAD

**Issue by ZellW** [Azure/Azure-TDSP-Utilities#32]
Is Microsoft going to continue to improve the TDSP Utilities?

**Comment by deguhath** [comment]
Thank you for your question. 

Currently, we have paused effort on development of new features or tools in this area. The purpose was to provide some good utility examples to get teams started, show some useful ways in R and Python data can be cleaned, summarized and reported on, and plant the concept that data science teams frequently need to have such utilities of common benefit. In many cases, depending on type of data (structured or unstructured), nature of business problem, such tools need to be customized. 

If you do have needs that could also benefit the community, please share and we will consider the suggestions for further development.

Thank you.
