### ISSUE TITLE
Unable to see the generate final button and also unable to find the intermediate .pynb files generated

### ISSUE THREAD

**Issue by lihka1** [Azure/Azure-TDSP-Utilities#34]
After running the cells in the IDEAR.ipynb in my local machine, I was unable to see the generate final report button and also the tmp export directory is empty.

Can anyone suggest me how to solve the issues i am facing.

Thanks in advance :)

By the way i am using ipywidgets 4.0...is there something to do with this?
I am unable to see most of the buttons in the scripts...

**Comment by wguo123** [comment]
@lihka1 can you update to the latest version of ipywidgets and give it another try?
