### ISSUE TITLE
Creating the "Export" Button

### ISSUE THREAD

**Issue by Pelonza** [Azure/Azure-TDSP-Utilities#35]
Running the IDEAR notebook in Python3 --- I did a conversion of all code files with 2to3, and am manually converting the prints in the notebook.

When trying to generate the widgets in "In[17]" ... the export button does not generate properly. 
I can still run that cell if I take the export button out of the code... but it means exporting any analysis is missing!

**Comment by Pelonza** [comment]
Specifically, when calling the "interactive" function, it reports back an error that:
ValueError: Button(description='Export', style=ButtonStyle()) cannot be transformed to a widget
Leading the call to fail, leaving no interactive generated.

**Comment by svanbodegraven** [comment]
Why was this issue closed?

**Comment by Pelonza** [comment]
I closed it because I _thought_ it had gotten fixed (when I ran a different
copy on another computer it worked ok).

Turns out... this isn't as fixed as I thought. I had a LOT of student still
having trouble with this export button.
I also had a lot of students have issues with missing packages etc (it'd be
good to have a "package check" at the beginning).

This code really isn't ready for prime-time in terms of "grab and go" for
use.

==================================================
To schedule a meeting or appointment try:
https://karlrbschmitt.youcanbook.me/

Dr. Karl Schmitt
Assistant Professor
Department of Mathematics and Statistics
Department of Computing and Information Sciences
Director of Data Science Program
Director of Analytics and Modeling Graduate Program
Valparaiso University, Indiana
==================================================
