### ISSUE TITLE
On Linux it doesn't generate the report

### ISSUE THREAD

**Issue by wilmeragsgh** [Azure/Azure-TDSP-Utilities#6]
As shown in [http://imgur.com/zlMQF0Ql.png](url) it doesn't generate the report although it's doing ok in the whole process. this is the yaml file that im using:
``DataFilePath:
    hour.csv
HasHeader:
    Yes
Separator:
    ','
Target:

ColumnsToExclude:
    instant
RLogFilePath:
    bikesharing-hour.log.r``

(for data exploration task)

thx in advance!

**Comment by hangzh-msft** [comment]
Hi, Wilmeragsgh,

Thanks for trying IDEAR and sorry to hear that the report was not generated in Linux.

In order for us to understand the issue, can you please provide more details?
1. Were you using x2go to access your Linux machine?
2. Were you running Run-IDEAR.R by **sourcing** the R file in RStudio?
3. Did you click Generate Report button to generate the report?

BTW, the png URL returns 404 error.

Thanks,

Hang

**Comment by hangzh-msft** [comment]
Closed this issue since the customer did not respond. Will reopen as needed.
