### ISSUE TITLE
Error package 'knitr' not found

### ISSUE THREAD

**Issue by rbobadilla** [Azure/Azure-TDSP-Utilities#7]
After selecting the YAML file, i got the following error:

Error package 'knitr' not found

This is the Console Output:

Warning: Error in utils::packageVersion: package ‘knitr’ not found
Stack trace (innermost first):
    109: utils::packageVersion
    108: knit_meta_reset
    107: render
    106: discover_rmd_resources
    105: find_external_resources
    104: copy_render_intermediates
    103: output_format$intermediates_generator
    102: <Anonymous>
    101: do.call
    100: contextFunc
     99: .getReactiveEnvironment()$runWith
     98: shiny::maskReactiveContext
     97: <reactive>
     86: doc
     85: shiny::renderUI
     84: func
     83: origRenderFunc
     82: output$__reactivedoc__
      7: <Anonymous>
      6: do.call
      5: rmarkdown::run
      4: eval [~/Team Data Science Process/Azure-TDSP-Utilities-master/DataScienceUtilities/DataReport-Utils/Run-IDEAR.R#14]
      3: eval
      2: withVisible
      1: source

What is wrong with it?

**Comment by symeprog** [comment]
You need to install the "knitr" package.

Try to execute this before running the rmarkdown document:
`install.packages('knitr')`

**Comment by xibingaomsft** [comment]
Hi @rbobadilla ,
Thanks for trying IDEAR.  Can you try installing knitr with install.packages('knitr') as @symeprog suggested?  It looks like knitr package is not installed correctly in your setup. Let me know if it solves the problem.
Xibin
