### ISSUE TITLE
Create Custom Visualization

### ISSUE THREAD

**Issue by CarlosAbramo** [Azure/Azure-TDSP-Utilities#9]
Hello,

Besides the great built-in visualizations available, is it possible (or planned) to create a custom dashboard with my preferred visualizations in a single page ? It should be great also to be possible to correlate the attributes in the dashboard as we do on PowerBI.

Best regards,

Carlos Abramo

**Comment by hangzh-msft** [comment]
Thanks for the suggestion. Currently we are trying to make it usable by everyone. We understand your request. It will be great if someone can contribute to this tool to make it connected to other data visualization tools.
